FROM ubuntu:20.04

RUN apt-get update && apt-get upgrade -yqq
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yqq git build-essential cmake gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf ninja-build
RUN apt-get update && apt-get install -yqq puredata

# clean apt cache and remove apt package lists
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
